import React from "react";
import * as Lucide from "lucide-react";

const ICON_KEYS = {
  outfits: "Shirt",
  planner: "CalendarDays",
  upgrade: "TrendingUp",
  theory: "BookOpen",
  rules: "Scale",
  presenter: "Presentation",
  minimal: "Circle",
  evening: "MoonStar",
  layered: "Layers",
  mover: "MoveRight",
  workshop: "Hammer",
  conference: "MicVocal",
  business: "BriefcaseBusiness",
  teambuilding: "Users",
  brunch: "Coffee",
  date: "Heart",
  dinner: "Utensils",
  citybreak: "MapPinned",
  party: "Sparkles",
  dayout: "Sun",
  indoor: "House",
  mild: "CloudSun",
  warm: "SunMedium",
  cold: "Snowflake",
  warning: "TriangleAlert",
  check: "BadgeCheck",
  close: "X",
  chevronDown: "ChevronDown",
  chevronRight: "ChevronRight",
  arrow: "ArrowRight",
  info: "Info",
  palette: "Palette",
  score: "Gauge",
  shoes: "Footprints",
  belt: "CircleEllipsis",
  layer: "Layers2",
  principles: "Compass",
  skintone: "ScanFace",
  seasons: "Leaf",
  clothes: "Shirt",
  materials: "Gem",
  grooming: "Scissors",
  fragrance: "Droplets",
  accessories: "Watch",
  chinofit: "Ruler",
  psychology: "Brain",
  confidence: "ShieldCheck",
  capsule: "Package",
};

export function Icon({ name, size = 18, color = "currentColor", strokeWidth = 1.9, style }) {
  const key = ICON_KEYS[name] || "Circle";
  const Component = Lucide[key] || Lucide.Circle;
  return React.createElement(Component, {
    size,
    color,
    strokeWidth,
    style,
    "aria-hidden": "true",
    focusable: "false",
  });
}
